//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class QBXML {
    
    private QBXMLQBXMLMsgsRs qBXMLMsgsRsField;
    
    /// <remarks/>
    public QBXMLQBXMLMsgsRs QBXMLMsgsRs {
        get {
            return this.qBXMLMsgsRsField;
        }
        set {
            this.qBXMLMsgsRsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class QBXMLQBXMLMsgsRs {
    
    private QBXMLQBXMLMsgsRsInvoiceAddRs invoiceAddRsField;
    
    /// <remarks/>
    public QBXMLQBXMLMsgsRsInvoiceAddRs InvoiceAddRs {
        get {
            return this.invoiceAddRsField;
        }
        set {
            this.invoiceAddRsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class QBXMLQBXMLMsgsRsInvoiceAddRs {
    
    private QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRet invoiceRetField;
    
    private string requestIDField;
    
    private byte statusCodeField;
    
    private string statusSeverityField;
    
    private string statusMessageField;
    
    /// <remarks/>
    public QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRet InvoiceRet {
        get {
            return this.invoiceRetField;
        }
        set {
            this.invoiceRetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string requestID {
        get {
            return this.requestIDField;
        }
        set {
            this.requestIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte statusCode {
        get {
            return this.statusCodeField;
        }
        set {
            this.statusCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string statusSeverity {
        get {
            return this.statusSeverityField;
        }
        set {
            this.statusSeverityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string statusMessage {
        get {
            return this.statusMessageField;
        }
        set {
            this.statusMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRet {
    
    private string txnIDField;
    
    private System.DateTime timeCreatedField;
    
    private System.DateTime timeModifiedField;
    
    private uint editSequenceField;
    
    private ushort txnNumberField;
    
    private QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetCustomerRef customerRefField;
    
    private QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetARAccountRef aRAccountRefField;
    
    private QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetTemplateRef templateRefField;
    
    private System.DateTime txnDateField;
    
    private ushort refNumberField;
    
    private QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetBillAddress billAddressField;
    
    private QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetShipAddress shipAddressField;
    
    private bool isPendingField;
    
    private bool isFinanceChargeField;
    
    private QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetTermsRef termsRefField;
    
    private System.DateTime dueDateField;
    
    private QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetSalesRepRef salesRepRefField;
    
    private System.DateTime shipDateField;
    
    private decimal subtotalField;
    
    private QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetItemSalesTaxRef itemSalesTaxRefField;
    
    private decimal salesTaxPercentageField;
    
    private decimal salesTaxTotalField;
    
    private decimal appliedAmountField;
    
    private decimal balanceRemainingField;
    
    private string memoField;
    
    private bool isPaidField;
    
    private bool isToBePrintedField;
    
    private QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetCustomerSalesTaxCodeRef customerSalesTaxCodeRefField;
    
    private QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetInvoiceLineRet invoiceLineRetField;
    
    /// <remarks/>
    public string TxnID {
        get {
            return this.txnIDField;
        }
        set {
            this.txnIDField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TimeCreated {
        get {
            return this.timeCreatedField;
        }
        set {
            this.timeCreatedField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TimeModified {
        get {
            return this.timeModifiedField;
        }
        set {
            this.timeModifiedField = value;
        }
    }
    
    /// <remarks/>
    public uint EditSequence {
        get {
            return this.editSequenceField;
        }
        set {
            this.editSequenceField = value;
        }
    }
    
    /// <remarks/>
    public ushort TxnNumber {
        get {
            return this.txnNumberField;
        }
        set {
            this.txnNumberField = value;
        }
    }
    
    /// <remarks/>
    public QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetCustomerRef CustomerRef {
        get {
            return this.customerRefField;
        }
        set {
            this.customerRefField = value;
        }
    }
    
    /// <remarks/>
    public QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetARAccountRef ARAccountRef {
        get {
            return this.aRAccountRefField;
        }
        set {
            this.aRAccountRefField = value;
        }
    }
    
    /// <remarks/>
    public QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetTemplateRef TemplateRef {
        get {
            return this.templateRefField;
        }
        set {
            this.templateRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime TxnDate {
        get {
            return this.txnDateField;
        }
        set {
            this.txnDateField = value;
        }
    }
    
    /// <remarks/>
    public ushort RefNumber {
        get {
            return this.refNumberField;
        }
        set {
            this.refNumberField = value;
        }
    }
    
    /// <remarks/>
    public QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetBillAddress BillAddress {
        get {
            return this.billAddressField;
        }
        set {
            this.billAddressField = value;
        }
    }
    
    /// <remarks/>
    public QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetShipAddress ShipAddress {
        get {
            return this.shipAddressField;
        }
        set {
            this.shipAddressField = value;
        }
    }
    
    /// <remarks/>
    public bool IsPending {
        get {
            return this.isPendingField;
        }
        set {
            this.isPendingField = value;
        }
    }
    
    /// <remarks/>
    public bool IsFinanceCharge {
        get {
            return this.isFinanceChargeField;
        }
        set {
            this.isFinanceChargeField = value;
        }
    }
    
    /// <remarks/>
    public QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetTermsRef TermsRef {
        get {
            return this.termsRefField;
        }
        set {
            this.termsRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DueDate {
        get {
            return this.dueDateField;
        }
        set {
            this.dueDateField = value;
        }
    }
    
    /// <remarks/>
    public QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetSalesRepRef SalesRepRef {
        get {
            return this.salesRepRefField;
        }
        set {
            this.salesRepRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ShipDate {
        get {
            return this.shipDateField;
        }
        set {
            this.shipDateField = value;
        }
    }
    
    /// <remarks/>
    public decimal Subtotal {
        get {
            return this.subtotalField;
        }
        set {
            this.subtotalField = value;
        }
    }
    
    /// <remarks/>
    public QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetItemSalesTaxRef ItemSalesTaxRef {
        get {
            return this.itemSalesTaxRefField;
        }
        set {
            this.itemSalesTaxRefField = value;
        }
    }
    
    /// <remarks/>
    public decimal SalesTaxPercentage {
        get {
            return this.salesTaxPercentageField;
        }
        set {
            this.salesTaxPercentageField = value;
        }
    }
    
    /// <remarks/>
    public decimal SalesTaxTotal {
        get {
            return this.salesTaxTotalField;
        }
        set {
            this.salesTaxTotalField = value;
        }
    }
    
    /// <remarks/>
    public decimal AppliedAmount {
        get {
            return this.appliedAmountField;
        }
        set {
            this.appliedAmountField = value;
        }
    }
    
    /// <remarks/>
    public decimal BalanceRemaining {
        get {
            return this.balanceRemainingField;
        }
        set {
            this.balanceRemainingField = value;
        }
    }
    
    /// <remarks/>
    public string Memo {
        get {
            return this.memoField;
        }
        set {
            this.memoField = value;
        }
    }
    
    /// <remarks/>
    public bool IsPaid {
        get {
            return this.isPaidField;
        }
        set {
            this.isPaidField = value;
        }
    }
    
    /// <remarks/>
    public bool IsToBePrinted {
        get {
            return this.isToBePrintedField;
        }
        set {
            this.isToBePrintedField = value;
        }
    }
    
    /// <remarks/>
    public QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetCustomerSalesTaxCodeRef CustomerSalesTaxCodeRef {
        get {
            return this.customerSalesTaxCodeRefField;
        }
        set {
            this.customerSalesTaxCodeRefField = value;
        }
    }
    
    /// <remarks/>
    public QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetInvoiceLineRet InvoiceLineRet {
        get {
            return this.invoiceLineRetField;
        }
        set {
            this.invoiceLineRetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetCustomerRef {
    
    private string listIDField;
    
    private string fullNameField;
    
    /// <remarks/>
    public string ListID {
        get {
            return this.listIDField;
        }
        set {
            this.listIDField = value;
        }
    }
    
    /// <remarks/>
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetARAccountRef {
    
    private string listIDField;
    
    private string fullNameField;
    
    /// <remarks/>
    public string ListID {
        get {
            return this.listIDField;
        }
        set {
            this.listIDField = value;
        }
    }
    
    /// <remarks/>
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetTemplateRef {
    
    private string listIDField;
    
    private string fullNameField;
    
    /// <remarks/>
    public string ListID {
        get {
            return this.listIDField;
        }
        set {
            this.listIDField = value;
        }
    }
    
    /// <remarks/>
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetBillAddress {
    
    private string addr1Field;
    
    private string addr2Field;
    
    private string cityField;
    
    private string stateField;
    
    private ushort postalCodeField;
    
    private string countryField;
    
    /// <remarks/>
    public string Addr1 {
        get {
            return this.addr1Field;
        }
        set {
            this.addr1Field = value;
        }
    }
    
    /// <remarks/>
    public string Addr2 {
        get {
            return this.addr2Field;
        }
        set {
            this.addr2Field = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public ushort PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetShipAddress {
    
    private string addr1Field;
    
    private string addr2Field;
    
    private string addr3Field;
    
    private string cityField;
    
    private string stateField;
    
    private ushort postalCodeField;
    
    private string countryField;
    
    /// <remarks/>
    public string Addr1 {
        get {
            return this.addr1Field;
        }
        set {
            this.addr1Field = value;
        }
    }
    
    /// <remarks/>
    public string Addr2 {
        get {
            return this.addr2Field;
        }
        set {
            this.addr2Field = value;
        }
    }
    
    /// <remarks/>
    public string Addr3 {
        get {
            return this.addr3Field;
        }
        set {
            this.addr3Field = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public ushort PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetTermsRef {
    
    private string listIDField;
    
    private string fullNameField;
    
    /// <remarks/>
    public string ListID {
        get {
            return this.listIDField;
        }
        set {
            this.listIDField = value;
        }
    }
    
    /// <remarks/>
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetSalesRepRef {
    
    private string listIDField;
    
    private string fullNameField;
    
    /// <remarks/>
    public string ListID {
        get {
            return this.listIDField;
        }
        set {
            this.listIDField = value;
        }
    }
    
    /// <remarks/>
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetItemSalesTaxRef {
    
    private string listIDField;
    
    private string fullNameField;
    
    /// <remarks/>
    public string ListID {
        get {
            return this.listIDField;
        }
        set {
            this.listIDField = value;
        }
    }
    
    /// <remarks/>
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetCustomerSalesTaxCodeRef {
    
    private string listIDField;
    
    private string fullNameField;
    
    /// <remarks/>
    public string ListID {
        get {
            return this.listIDField;
        }
        set {
            this.listIDField = value;
        }
    }
    
    /// <remarks/>
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetInvoiceLineRet {
    
    private string txnLineIDField;
    
    private QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetInvoiceLineRetItemRef itemRefField;
    
    private string descField;
    
    private byte quantityField;
    
    private decimal rateField;
    
    private decimal amountField;
    
    private QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetInvoiceLineRetSalesTaxCodeRef salesTaxCodeRefField;
    
    /// <remarks/>
    public string TxnLineID {
        get {
            return this.txnLineIDField;
        }
        set {
            this.txnLineIDField = value;
        }
    }
    
    /// <remarks/>
    public QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetInvoiceLineRetItemRef ItemRef {
        get {
            return this.itemRefField;
        }
        set {
            this.itemRefField = value;
        }
    }
    
    /// <remarks/>
    public string Desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
    
    /// <remarks/>
    public byte Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    public decimal Rate {
        get {
            return this.rateField;
        }
        set {
            this.rateField = value;
        }
    }
    
    /// <remarks/>
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    public QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetInvoiceLineRetSalesTaxCodeRef SalesTaxCodeRef {
        get {
            return this.salesTaxCodeRefField;
        }
        set {
            this.salesTaxCodeRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetInvoiceLineRetItemRef {
    
    private string listIDField;
    
    private string fullNameField;
    
    /// <remarks/>
    public string ListID {
        get {
            return this.listIDField;
        }
        set {
            this.listIDField = value;
        }
    }
    
    /// <remarks/>
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class QBXMLQBXMLMsgsRsInvoiceAddRsInvoiceRetInvoiceLineRetSalesTaxCodeRef {
    
    private string listIDField;
    
    private string fullNameField;
    
    /// <remarks/>
    public string ListID {
        get {
            return this.listIDField;
        }
        set {
            this.listIDField = value;
        }
    }
    
    /// <remarks/>
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
}
